In [1]:
pwd

'/Users/mayragavilan/Documents/GitHub/Diplomado_PUCP/Lecture_9/Assignment_7'

In [2]:
import pandas as pd

health_estb = pd.read_excel(r'../../_data/cajamarca_data_helth_estb.xlsx')

districts = pd.read_excel(r'../../_data/peru_districts_centroids.xlsx')

cajamarca_districts = districts[districts['NOMBDEP'] == 'CAJAMARCA']

In [17]:
from tqdm import tqdm
import numpy as np

# Crear un nuevo DataFrame para almacenar los resultados
result_df = cajamarca_districts.copy()

# Crear nuevas columnas en 'result_df' para almacenar el establecimiento de salud más cercano
result_df['closest_health_estb'] = np.nan
result_df['closest_health_estb_lat'] = np.nan
result_df['closest_health_estb_lon'] = np.nan

# Iterar sobre cada fila en 'result_df'
for index, district_row in tqdm(result_df.iterrows(), total=len(result_df), desc="Finding closest health establishment"):
    district_coords = (district_row['Centroid_Latitude'], district_row['Centroid_Longitude'])
    
    # Calcular la distancia euclidiana para cada establecimiento de salud y encontrar el más cercano
    min_distance = float('inf')
    closest_health_estb = None
    closest_health_estb_lat = None
    closest_health_estb_lon = None
    
    for _, health_row in health_estb.iterrows():
        health_coords = (health_row['latitud'], health_row['longitud'])
        distance = np.linalg.norm(np.array(district_coords) - np.array(health_coords))
        
        if distance < min_distance:
            min_distance = distance
            closest_health_estb = health_row['nombre']
            closest_health_estb_lat = health_row['latitud']
            closest_health_estb_lon = health_row['longitud']
    
    # Almacenar el establecimiento de salud más cercano en las nuevas columnas
    result_df.at[index, 'closest_health_estb'] = closest_health_estb
    result_df.at[index, 'closest_health_estb_lat'] = closest_health_estb_lat
    result_df.at[index, 'closest_health_estb_lon'] = closest_health_estb_lon

# Ahora 'result_df' contiene los resultados sin afectar 'cajamarca_districts'
result_df

Finding closest health establishment:   0%|             | 0/127 [00:00<?, ?it/s]/var/folders/n_/qpz2jhwn79n2g_ymfrydlg9w0000gn/T/ipykernel_17548/19736980.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'TOTORILLAS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  result_df.at[index, 'closest_health_estb'] = closest_health_estb
Finding closest health establishment: 100%|███| 127/127 [00:09<00:00, 13.60it/s]

,CCDD,NOMBDEP,CCPP,NOMBPROV,CCDI,NOMBDIST,CAPITAL,UBIGEO,IDPROV,CODIGO,Centroid_Latitude,Centroid_Longitude,closest_health_estb,closest_health_estb_lat,closest_health_estb_lon
0,6,CAJAMARCA,5,CONTUMAZA,4,GUZMANGO,GUZMANGO,60504,605,60504,-7.364304,-78.917689,TOTORILLAS,-7.353468,-78.930011
1,6,CAJAMARCA,11,SAN MIGUEL,5,EL PRADO,EL PRADO,61105,611,61105,-7.038039,-79.003318,EL PRADO,-7.033193,-79.009410
2,6,CAJAMARCA,11,SAN MIGUEL,9,NIEPOS,NIEPOS,61109,611,61109,-6.926718,-79.131435,NIEPOS,-6.926729,-79.128402
3,6,CAJAMARCA,11,SAN MIGUEL,10,SAN GREGORIO,SAN GREGORIO,61110,611,61110,-7.117978,-79.160968,EL SAUCE,-7.063950,-79.127350
4,6,CAJAMARCA,12,SAN PABLO,3,SAN LUIS,SAN LUIS GRANDE,61203,612,61203,-7.159046,-78.873084,SAN LUIS BAJO - GRANDE,-7.156648,-78.869062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,6,CAJAMARCA,3,CELENDIN,8,OXAMARCA,OXAMARCA,60308,603,60308,-7.059289,-78.061333,LA QUINUA,-7.072427,-78.054640
1645,6,CAJAMARCA,3,CELENDIN,9,SOROCHUCO,SOROCHUCO,60309,603,60309,-6.934215,-78.297182,LA CHORRERA,-6.950057,-78.315067
1743,6,CAJAMARCA,8,JAEN,10,SAN FELIPE,SAN FELIPE,60810,608,60810,-5.786477,-79.310211,SAN FELIPE,-5.770258,-79.312835
1744,6,CAJAMARCA,8,JAEN,6,LAS PIRIAS,LAS PIRIAS,60806,608,60806,-5.636342,-78.849590,LAS PIRIAS DE JAEN,-5.627073,-78.852416
1762,6,CAJAMARCA,6,CUTERVO,6,PIMPINGOS,PIMPINGOS,60606,606,60606,-6.070895,-78.768292,PIMPINCOS,-6.060707,-78.756689

In [21]:
# Before find the driving travel time and distance from health establishments to district centroids, made some
# changes to dataframe 'result_df'to get the coordinates
result_df['Distrito_coord'] = result_df['Centroid_Latitude'].astype(str) + ',' + result_df['Centroid_Longitude'].astype(str)
result_df['EESS_coord'] = result_df['closest_health_estb_lat'].astype(str) + ',' + result_df['closest_health_estb_lon'].astype(str)
result_df.rename(columns={'NOMBPROV': 'Provincia', 'NOMBDIST': 'Distrito', 'closest_health_estb':'Centro de salud'}, inplace=True)
result_df2 = result_df[['Provincia', 'Distrito', 'Centro de salud', 'EESS_coord', 'Distrito_coord']]
result_df2

,Provincia,Distrito,Centro de salud,EESS_coord,Distrito_coord
0,CONTUMAZA,GUZMANGO,TOTORILLAS,"-7.3534676,-78.93001098","-7.364304037451185,-78.9176888857091"
1,SAN MIGUEL,EL PRADO,EL PRADO,"-7.033193,-79.00941","-7.038039308001461,-79.00331840461457"
2,SAN MIGUEL,NIEPOS,NIEPOS,"-6.9267286,-79.12840201","-6.926717799126992,-79.13143524251483"
3,SAN MIGUEL,SAN GREGORIO,EL SAUCE,"-7.06395,-79.12735","-7.117978014363154,-79.16096822944561"
4,SAN PABLO,SAN LUIS,SAN LUIS BAJO - GRANDE,"-7.1566476,-78.8690618","-7.159045931055743,-78.8730841197766"
...,...,...,...,...,...
1644,CELENDIN,OXAMARCA,LA QUINUA,"-7.07242673,-78.05464005","-7.059288980121174,-78.06133279004958"
1645,CELENDIN,SOROCHUCO,LA CHORRERA,"-6.95005723,-78.31506737","-6.934214997604489,-78.29718227998802"
1743,JAEN,SAN FELIPE,SAN FELIPE,"-5.77025781,-79.31283463","-5.786477227250232,-79.31021142229889"
1744,JAEN,LAS PIRIAS,LAS PIRIAS DE JAEN,"-5.62707293,-78.8524157","-5.636341962042768,-78.84958991537201"
1762,CUTERVO,PIMPINGOS,PIMPINCOS,"-6.06070669,-78.75668917","-6.07089520466843,-78.76829226789994"

In [22]:
import requests
import re

# Create a empty data frame 
distancias_df = pd.DataFrame(columns=['Provincia','Distrito', 'Centro de salud', 'Modo de trafico', 'Duracion (min)', 'Distancia (km)'])

# set variables for the API request
endpoint = 'https://maps.googleapis.com/maps/api/directions/json?'
traffic_models = ['best_guess', 'pessimistic', 'optimistic'] 
departure_time = '1707148800'  # Monday February 5, 2024, 4 pm
mode = 'driving'
api_key = 'AIzaSyAIyJDcD4PZsu2mSLcMwHyifePf6pPkRsU'
region = 'PE'

rows_list = []

# Loop that iterates over the DataFrame result_df2 and traffic_models
for _, row_coord in result_df2.iterrows():
    for traffic_model in traffic_models:
        EESS_coord = row_coord['EESS_coord']
        Distrito_coord = row_coord['Distrito_coord']

        nav_request = f'origin={Distrito_coord}&destination={EESS_coord}&departure_time={departure_time}&traffic_model={traffic_model}&mode={mode}&region={region}&key={api_key}'
        request = endpoint + nav_request

        response = requests.get(request)
        directions = response.json()
        
        # Extract trip duration
        if 'routes' in directions and len(directions['routes']) > 0 and 'legs' in directions['routes'][0] and len(directions['routes'][0]['legs']) > 0:
            duracion_texto = directions['routes'][0]['legs'][0]['duration']['text']

            match = re.match(r'(\d+) hour(?:s)? (\d+) min(?:ute)?', duracion_texto)

            if match:
                horas, minutos = map(int, match.groups())
                duracion_min_num = horas * 60 + minutos
            else:
                duracion_min_num = int(re.match(r'(\d+) min(?:ute)?', duracion_texto).group(1))
        else:
            duracion_min_num = None
        
        # Extract trip distance
        if 'routes' in directions and len(directions['routes']) > 0 and 'legs' in directions['routes'][0] and len(directions['routes'][0]['legs']) > 0:
            distancia = directions['routes'][0]['legs'][0]['distance']['text']
        else:
            distancia = None

        row_dict = {
            'Provincia':row_coord['Provincia'],
            'Distrito': row_coord['Distrito'],
            'Centro de salud': row_coord['Centro de salud'],
            'Modo de trafico': traffic_model,
            'Duracion (min)': duracion_min_num,
            'Distancia (km)': distancia
        }
        rows_list.append(row_dict)

# Concatenate list of rows into distances_df data frame
distancias_df = pd.concat([distancias_df, pd.DataFrame(rows_list)])
distancias_df

/var/folders/n_/qpz2jhwn79n2g_ymfrydlg9w0000gn/T/ipykernel_17548/512528188.py:54: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  distancias_df = pd.concat([distancias_df, pd.DataFrame(rows_list)])

,Provincia,Distrito,Centro de salud,Modo de trafico,Duracion (min),Distancia (km)
0,CONTUMAZA,GUZMANGO,TOTORILLAS,best_guess,4.0,1.3 km
1,CONTUMAZA,GUZMANGO,TOTORILLAS,pessimistic,4.0,1.3 km
2,CONTUMAZA,GUZMANGO,TOTORILLAS,optimistic,4.0,1.3 km
3,SAN MIGUEL,EL PRADO,EL PRADO,best_guess,7.0,2.6 km
4,SAN MIGUEL,EL PRADO,EL PRADO,pessimistic,7.0,2.6 km
...,...,...,...,...,...,...
376,JAEN,LAS PIRIAS,LAS PIRIAS DE JAEN,pessimistic,4.0,1.6 km
377,JAEN,LAS PIRIAS,LAS PIRIAS DE JAEN,optimistic,4.0,1.6 km
378,CUTERVO,PIMPINGOS,PIMPINCOS,best_guess,8.0,2.8 km
379,CUTERVO,PIMPINGOS,PIMPINCOS,pessimistic,8.0,2.8 km
380,CUTERVO,PIMPINGOS,PIMPINCOS,optimistic,8.0,2.8 km